### ISSUE TITLE
Error while running cc benchmark from GAPBS

### ISSUE THREAD

**Issue by akshaybaviskar** [technion-csl/mosmodel#18]
Hello @idanyani and @magbarya,

I ran cc benchmark with Twitter dataset as input from gapbs benchmark suite.

I got following error on running it :
```
Traceback (most recent call last):
  File "/home/akshaybavisk/mosmodel/cc_twit_working/scripts/runBenchmark.py", line 103, in <module>
    benchmark_run.wait()
  File "/home/akshaybavisk/mosmodel/cc_twit_working/scripts/runBenchmark.py", line 51, in wait
    raise subprocess.CalledProcessError(self._run_process.returncode, ' '.join(self._run_process.args))
subprocess.CalledProcessError: Command '/home/akshaybavisk/mosmodel/cc_twit_working/scripts/measureGeneralMetrics.sh /home/akshaybavisk/mosmodel/cc_twit_working/scripts/setCpuMemoryAffinity.sh 1 /home/akshaybavisk/mosmodel/cc_twit_working/mosalloc/runMosalloc.py --library /home/akshaybavisk/mosmodel/cc_twit_working/mosalloc/src/libmosalloc.so -fps 1GB -aps 107374182400 -as1 0 -ae1 0 -as2 0 -ae2 107374182400 -bps 4194304 -bs1 0 -be1 0 -bs2 0 -be2 4194304 --analyze ./run.sh' returned non-zero exit status 127.
make: *** [/home/akshaybavisk/mosmodel/cc_twit_working/experiments/template.mk:35: experiments/single_page_size/layout2mb/repeat1/perf.out] Error 1

```
I have attached the complete log [here](https://github.com/technion-csl/mosmodel/files/7170071/makelog.txt)

What could be the reason behind this?

Thanks,
Akshay

**Comment by magbarya** [comment]
Hi Akshay,
I have tried to reproduce this issue but unfortunately could not. The cc-twitter benchmark runs, for me, without any failures.
Actually, I noticed that the benchmark memory footprint, from your log, is incorrect for some reason.
Can you please:
1) attach the following two files:
experiments/without_mosalloc/repeat1/time.out
experiments/without_mosalloc/repeat1/max_mem.txt
2) try to run "make clean" and then "make" again

**Comment by akshaybaviskar** [comment]
Hello Mohammad,

Sorry for the late reply. 
Please find the files attached.
[max_mem.txt](https://github.com/technion-csl/mosmodel/files/7267570/max_mem.txt)
[time.out.txt](https://github.com/technion-csl/mosmodel/files/7267576/time.out.txt)

I get the same error if I run make clean and make again.

Thanks,
Akshay

**Comment by idanyani** [comment]
@magbarya : maybe this is the same bug of issue #16 ?
@akshaybaviskar : can you please pull the latest commit and try again?

**Comment by magbarya** [comment]
@idanyani: it could be related to #16, but I see another problem from the logs so I want to isolate the issue that Akshay observes.

@akshaybaviskar: I can see two issues by looking at the attached files. 
1) I can see in the log that the benchmark footprint (the anonymous pool size when running the 2MB layout) is 100 GB, which does not make sense. 
2) I can see too that the "without_mosalloc" experiment was failed (you can see the exit code in the time.out file). 
Can you please try to run the run.sh script, which runs the cc-twitter, just to make sure that it runs with no errors.
